export enum ApiErrors {
  API_KEY_MISSING = "API_KEY_MISSING",
  API_REQUEST_FAILED = "API_REQUEST_FAILED",
  INVALID_API_RESPONSE = "INVALID_API_RESPONSE",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  UNAUTHORIZED = "UNAUTHORIZED",
}
