export enum AppErrors {
  INVALID_CHANNEL_URL = "INVALID_CHANNEL_URL",
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
  ANALYSIS_FAILED = "ANALYSIS_FAILED",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  CHANNEL_URL_REQUIRED = "CHANNEL_URL_REQUIRED",
}
